config/routes.rb
Rails.application.routes.draw do
  
  
  
resources :orders

  resources :order_items

  resources :carts

  get 'store/index'

  resources :products 

  get 'sessions/new'

  get 'users/new'
  
  get 'store'  => 'store#index'

  root             'static_pages#home'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup'   => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  get 'bicycles' => 'static_pages#bicycles'
  get 'parts' => 'static_pages#parts'
  get 'repairs' => 'static_pages#repairs'
  get 'gear' => 'static_pages#gear'
  delete 'logout'  => 'sessions#destroy'
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]

  

end

app/views/layouts/_cart.html.erb
<div class="cart_title"></div>


<table>
  <%= render(cart.order_items) %>
  
  <tr class="total_line">
    <td colspan="2">Total</td>
    <td class="total_cell"><%= number_to_currency (cart.total_price) %></td>
  </tr>
</table>

<%= button_to "Checkout", new_order_path, method: :get %>
<%= button_to 'Empty cart', cart, method: :delete,
    confirm: 'Are you sure?' %>
<%= button_to 'Continue Shopping', store_path, :method => "get" %>

app/views/layouts/_cart_small.html.erb
   <div id="columns">
<div id="side">
<div id="cart">
 <%= render @cart %>
 </div>

app/views/layouts/_cart_text.html.erb
<%#= link_to "#{current_cart.order_items.size} Items in Cart ( #{number_to_currency current_order.subtotal} )", carts_path, class: "btn btn-link" %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Tadhg and Piotrs <a href="http://en.wikipedia.org/wiki/Bicycle">Bicycle</a> Shop
    
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://en.wikipedia.org/wiki/Bicycle">Bicycles</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Tadhg and Piotr's Bicycle Shop", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        
         
        <% else if logged_in? %>
        <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Products", products_path %></li>
          <li><%= link_to "Store", store_path %></li>
          <li><%= link_to "Orders", orders_path %></li>
          <li><%#= link_to "Cart", cart_path %></li>
          <li><%= render 'layouts/cart_text' %></li>
          <li><%= link_to "Users", users_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Sign up!", signup_path %></li>
          <li><%= link_to "Log in", login_path %></li>
          <li><%= link_to "Store", store_path %></li>
        <% end %>
        
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag 'application', media: 'all',
                                           'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <%#= render 'layouts/cart_small' %>
    
    
          

    <div class="container">
            <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>

      <%= yield %>
     
     </div>
     <%= render 'layouts/footer' %>
     <%= debug(params) if Rails.env.development? %>
  </body>
      

</html>